In this project you going to implement some basics of numpy that you learnt till now.

# Numpy
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

## 1. Numpy Array
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
import numpy as np

# Q1. Create a rank 1 array with elements 1,2,3 (1 marks)

## start code here
a = np.array([1,2,3])

# Q2. print its type and shape (1 marks)

## Start code here
print(type(a))
print(a.shape)

# Q3. Print each of its element individually (1 marks)

## Start code here
for element in a:
    print(element)

# Q4. Change element of the array at zero index with 5  (1 marks)

## Start code here
a[0] = 5

# print new array

# Q5. Create a rank 2 array like [[1,2,3],[4,5,6]]  (1 marks)

## Start code here
b = np.array([[1,2,3],[4,5,6]])

# Q6. print its shape (1 marks)

print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

print(b.shape)

<class 'numpy.ndarray'>
(3,)
1
2
3
1 2 4
(2, 3)


Numpy also provides many functions to create arrays:

In [ ]:
# Q1. Create an array of all zeros with shape (2,2) (1 marks)
## Start code here
a = np.zeros((2,2))
print(a)

# Q2. Create an array of all ones with shape (1,2) (1 marks)
## Start code here
b = np.ones((1,2))
print(b)

# Q3. Create a constant array with shape (2,2) and value 7 (1 marks)
## Start code here
c =  np.full((2,2), 7)
print(c)

# Q4. Create a 2x2 identity matrix (1 marks)
## Start code here
d = np.eye(2)
print(d)

# Q5. Create an (2,2) array filled with random values (1 marks)
## Start code here
e = np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.71411342 0.51170518]
 [0.69751136 0.52486769]]


You can read about other methods of array creation in the documentation in the link below.

http://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation

## 2. Array indexing
Numpy offers several ways to index into arrays.

**a) Slicing:** Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
# Q1. Create the following rank 2 array with shape (3, 4) and values as given below (1 mark)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# Start code here
a =

# Q2. Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2): (1 mark)

# Start code here
b =

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [ ]:
# Q1. Create the following rank 2 array with shape (3, 4) value as given below (1 marks)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

# Start code here
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the original array:

# Q2. Create Rank 1 view of the second row of a (1 marks)
# Start code here
row_r1 = a[1]

# Q3. # Create Rank 2 view of the second row of a (1 marks)
# Start code here
row_r2 = a[1:2]

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
# We can make the same distinction when accessing columns of an array:

# Q4. Create Rank 1 view of the second column of a (1 marks)
# Start code here
col_r1 = a[:, 1]

# Q5. Create Rank 2 view of the second column of a (1 marks)
# Start code here
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**b) Integer array indexing:** When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# Using the array "a" created above and integer indexing

# Q1. print an array  that should have shape (3,) and should print "[1 4 5]" when printed (1 marks)
## Start code
result_q1 = np.array([a[0, 0], a[1, 1], a[2, 0]])
print(result_q1)
# The method of integer array indexing that you implemented is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:

# Q2. Print the array that prints "[2 2]" when printed (1 marks)

## Start code
result_q2 = np.array([a[0, 1], a[0, 1]])
print(result_q2)

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)


# Create an array of indices
b = np.array([0, 2, 0, 1])

# Q1. Select one element from each row of a using the indices in b and print it (1 marks)
## Start code
selected_elements = a[np.arange(len(a)), b]
print(selected_elements)

# Q2. Mutate one element from each row of a using the indices in b by adding 10 to it and print it (1 marks)
## Start code
a[np.arange(len(a)), b] += 10
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**c) Boolean array indexing:** Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])

# Q1. Find the elements of a that are bigger than 2 using boolean indexing (1 marks)
## Start code
bool_idx = a > 2

print(bool_idx)

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation from the given link.
http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

## 3. Datatypes
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64
float64
int64


You can read all about numpy datatypes in the documentation from the given link.
http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html

## 4. Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Q1. print Elementwise sum of x and y (1 marks)
## Start code here
sum = x + y
print(sum)
# Q2. print Elementwise difference of x and y (1 marks)
## Start code here
diff = x - y
print(diff)
# Q3. print Elementwise product of x and y (1 marks)
## Start code here
product = x * y
print(product)
# Q4. print Elementwise divison of x and y (1 marks)
## Start code here
division = x / y
print(division)
# Q5. print Elementwise square root of x (1 marks)
## Start code here
sqrt = np.sqrt(x)
print(sqrt)

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Q1. print Inner product of vectors v and w; (1 marks)
## Start code here
inner_product = np.dot(v, w)
print(inner_product)
# Q2. print Matrix / vector product of x and v; (1 marks)
## Start code here
result_vector = np.dot(x, v)
print(result_vector)
# Q3. print Matrix / matrix product of x and y; (1 marks)
## Start code here
result_matrix = np.dot(x, y)
print(result_matrix)

219
[29 67]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [ ]:
x = np.array([[1,2],[3,4]])

# Q1. Compute sum of all elements and print it (1 marks)
## Start code here
total_sum = np.sum(x)
print(total_sum)

# Q2. Compute sum of each column and print it (1 marks)
## Start code here
column_sums = np.sum(x, axis=0)
print(column_sums)

# Q3. Compute sum of each row and print it (1 marks)
## Start code here
row_sums = np.sum(x, axis=1)
print(row_sums)

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the documentation on the provided link.
http://docs.scipy.org/doc/numpy/reference/routines.math.html

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
x = np.array([[1,2], [3,4]])

# Q1. print x and its transpose (2 marks)
## Start code here
x_transpose = np.transpose(x)
print("Matrix x:")
print(x)
print("Transpose of x:")
print(x_transpose)
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])

# Q2. print v and its transpose (2 marks)
## Start code here
v_transpose = np.transpose(v)
print("Vector v:")
print(v)
print("Transpose of v (same as v):")
print(v_transpose)

Matrix x:
[[1 2]
 [3 4]]
Transpose of x:
[[1 3]
 [2 4]]
Vector v:
[1 2 3]
Transpose of v (same as v):
[1 2 3]


Numpy provides many more functions for manipulating arrays; you can see the full list in the documentation on the provided link.
http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html

## 5. Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
# You will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Q1. Add the vector v to each row of the matrix x with an explicit loop and store in y (2 marks)
## Start code here
for i in range(len(x)):
    y[i] = x[i] + v

print("Matrix y (result of adding v to each row of x):")
print(y)

Matrix y (result of adding v to each row of x):
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix *x* is very large, computing an explicit loop in Python could be slow. Note that adding the vector *v* to each row of the matrix *x* is equivalent to forming a matrix *vv* by stacking multiple copies of v vertically, then performing elementwise summation of *x* and *vv*. We could implement this approach like this:

In [ ]:
# You will add the vector v to each row of the matrix x,
# storing the result in the matrix y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Q1. Stack 4 copies of v on top of each other using tile method and store it in vv. (2 marks)
## Start code here
vv = np.tile(v, (4, 1))
print(vv)

# Q2. Add x and vv elementwise (1 marks)
## Start code here
y = x + vv
print(y)



[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of *v*. Consider this version, using broadcasting:

In [ ]:
# You will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Q1. Add v to each row of x using broadcasting (2 marks)
## Start code here
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

> If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.

>The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.

>The arrays can be broadcast together if they are compatible in all dimensions.

>After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.

>In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.

>If this explanation does not make sense, try reading the explanation from the documentation or this explanation.http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc

>Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the documentation from the link provided.
http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs

Here are some applications of broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

# Q1. Compute an outer product of v and w and print it (hint:we first reshape v to be a column) (2 marks)
## Start code here
outer_product = np.dot(v[:, np.newaxis], w[np.newaxis, :])
print("Outer product of v and w:")
print(outer_product)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])

# Q2. Add v to ecah row of x and print it (2 marks)
## Start code here
x_with_v = x + v # Remove the reshaping of v
print("Matrix x with v added to each row:")
print(x_with_v)
# Add a vector to each column of a matrix
# Q3. Add vector w to each column of x and print it (1 marks)
x_with_w = x + np.reshape(w, (2, 1))
print("Matrix x with w added to each column:")
print(x_with_w)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

Outer product of v and w:
[[ 4  5]
 [ 8 10]
 [12 15]]
Matrix x with v added to each row:
[[2 4 6]
 [5 7 9]]
Matrix x with w added to each column:
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

## 6. Numpy Documentation
This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the numpy reference to find out much more about numpy.
http://docs.scipy.org/doc/numpy/reference/

# 7. Conclusion

In [ ]:
# write your conclusions here